import timer from "./modules/timer.js";
import menu from "./modules/menu.js";
import modal from "./modules/modal.js";
import calc from "./modules/calc.js";
import validationForm from "./modules/validationForm.js";
import tabs from "./modules/tabs.js";
import slider from "./modules/slider.js";
import sendForm from "./modules/sendForm.js";

timer("15 january 2022");
menu();
modal();
calc(100);
validationForm("form1");
validationForm("form2");
validationForm("form3");
tabs();
slider();
sendForm("form1");
sendForm("form2");
sendForm("form3");
